server:
  servlet:
    context-path: /linker-server
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  port: 8888
spring:
  application:
    name: Linker

logging:
  file:
    path: ./logs
