server:
  servlet:
    context-path: /linker-server
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  port: 8888
spring:
  application:
    name: Linker
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
  mvc:
    converters:
      preferred-json-mapper: jackson

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  file:
    path: ./logs
