spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  mvc:
    converters:
      preferred-json-mapper: jackson
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_linker?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
  lifecycle:
    timeout-per-shutdown-phase: 60
mybatis:
  type-aliases-package: com.equator.linker.model.po
  configuration:
    map-underscore-to-camel-case: true
linker:
  security:
    md5-salt: LYcuh0TA8q7w
    des-key: 0pe.*VZk
  base:
    env: local
server:
  shutdown: graceful

logging:
  level:
    root: info
    com.equator.linker.dao: debug